### ISSUE TITLE
Statefulset Problem

### ISSUE THREAD

**Issue by NahaliY** [galexrt/kubernetes-keycloak#5] opened 2019-04-25 14:12 UTC
I have a problem when deploying the statefulset.yaml file. Pods still in creatingContainer state 

> Warning	FailedMount	MountVolume.SetUp failed for volume "keycloak-scripts" : configmap references non-existent config key: REPLICAS	7 minutes ago
Warning	FailedMount	Unable to mount volumes for pod "keycloak-0_default(3a010ebf-6762-11e9-b9e2-005056a67a77)": timeout expired waiting for volumes to attach or mount for pod "default"/"keycloak-0". list of unmounted volumes=[keycloak-scripts]. list of unattached volumes=[keycloak-scripts default-token-dhqb6]	7 minutes ago
Normal	Scheduled	Successfully assigned default/keycloak-0 to k8s-worker2	5 minutes ago
Warning	FailedMount	Unable to mount volumes for pod "keycloak-0_default(3a010ebf-6762-11e9-b9e2-005056a67a77)": timeout expired waiting for volumes to attach or mount for pod "default"/"keycloak-0". list of unmounted volumes=[keycloak-scripts default-token-dhqb6]. list of unattached volumes=[keycloak-scripts default-token-dhqb6]	5 minutes ago
Warning	FailedMount	Unable to mount volumes for pod "keycloak-0_default(746a964c-6763-11e9-b9e2-005056a67a77)": timeout expired waiting for volumes to attach or mount for pod "default"/"keycloak-0". list of unmounted volumes=[keycloak-scripts]. list of unattached volumes=[keycloak-scripts default-token-dhqb6]	3 minutes ago
Warning	FailedMount	MountVolume.SetUp failed for volume "keycloak-scripts" : configmap references non-existent config key: REPLICAS	2 minutes ago
Normal	Scheduled	Successfully assigned default/keycloak-0 to k8s-worker2	a minute ago
Warning	FailedMount	MountVolume.SetUp failed for volume "keycloak-scripts" : configmap "keycloak-scripts-cm" not found	a minute ago 

>

**Comment by jakehamilton** [comment] 2020-01-05 22:16
It looks like the config map was not created. Are you sure that you've run `kubectl apply -f configmap.yaml`?

You can try running `kubectl get cm` to check for the resource.

**Comment by galexrt** [comment] 2020-03-04 08:07
As @jakehamilton wrote make sure you have created all objects from the manifests (e.g., `kubectl create -f .` in the repo root).

Though to note is that this repo is "outdated" (still using Keycloak 3.4.2).

***

Closing as not reproducible on my end.

**Closed as completed by galexrt** 2020-03-04 08:07 UTC
